config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pujas
  resources :pictures
  root 'lineages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
   mount_uploader :picture_image, PictureImageUploader
end

app/models/puja.rb
class Puja < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :benefit, presence: true
  validates :suggested_offering, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def facebook
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lineages_controller.rb
class LineagesController < ApplicationController
  def index
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
   @pictures = Picture.all.order("created_at DESC")
  end

  def show
   @picture = Picture.find(params[:id])
 end

  def create
    @picture = Picture.new(picture_params)

    @picture.save
    redirect_to @picture
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])

    if @picture.update(picture_params)
      redirect_to pictures_path
    else
      render 'edit'
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    redirect_to pictures_path
  end

  private
    def picture_params
      params.require(:picture).permit(:title, :description, :picture_image)
    end

end

app/controllers/pujas_controller.rb
class PujasController < ApplicationController
  def index
   @pujas = Puja.all
 end
  def new

  end

  def show
    @puja = Puja.find(params[:id])
  end



  def create
    @puja = Puja.new(puja_params)
    @puja.save
    redirect_to @puja
  end

  def update
    @puja = Puja.find(params[:id])

    if @puja.update(puja_params)
      redirect_to pujas_path
    else
      render 'edit'
    end
  end

  def edit
  @puja = Puja.find(params[:id])
end

  def destroy
    @puja = Puja.find(params[:id])
    @puja.destroy

    redirect_to pujas_path
  end

  private
    def puja_params
      params.require(:puja).permit(:name, :description, :benefit, :suggested_offering)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lineages_helper.rb
module LineagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/pujas_helper.rb
module PujasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buddhism</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lineages/index.html.erb
<h1>Lineages index</h1>

<p>༄༅། །རྫོགས་ཆེན་སྨོན་ལམ་བཞུགས།<br>
Dzogchen Aspiration Prayer</p>

<p>འཁོར་འདས་མཉམ་ཉིད་ལྟ་བའི་གདིངས་ཆེན་ཐོབ། ། <br>
khor dé nyam nyi tawé ding chen tob <br>
May we obtain the great confidence of the View of the perfect equality of both saṃsāra and nirvāṇa.</p>

<p>མ་བཅོས་རང་བབས་སྒོམ་པའི་རྩལ་ཆེན་རྫོགས། ། <br>
ma chö rang bab gompé tsal chen dzok <br>
May we greatly perfect and strengthen Meditation, which is naturally resting in the unaltered state.</p>

<p>བྱར་མེད་ཤུགས་འབྱུང་སྤྱོད་པའི་བོགས་ཆེན་འབྱོངས། ། <br>
char mé shukjung chöpé bok chen jong <br>
May we gain greater skill in the Action, which is natural and spontaneous non-action. </p>

<p> སྤང་ཐོབ་བྲལ་བའི་ཆོས་སྐུ་རང་རྙེད་ཤོག ། <br>
pang tob dralwé chöku rang nyé shok <br>
May we naturally discover the Dharmakāya, which is beyond gaining and losing. </p>

<P> By Dudjom Rinpoche </p>



<%= link_to 'See Available Puja', pujas_path %>

<%= link_to 'See Pictures', pictures_path %>

app/views/pictures/edit.html.erb
<h1>Edit picture here</h1>



<%= form_for :picture, url: picture_path(@picture), method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :picture_image %>
    <%= f.file_field :image, title: "Please choose file", class: "file-picker" %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', pictures_path %>

<script>
    displayFile = (object) ->
      file = object.value.split("\\")
      filename = file[file.length-1]
      $("#file-name").text(filename)

    $("#file-btn").on "click", ->
      $("#file-picker").click()

    $("#file-picker").on "change", ->
      displayFile(this)
  </script>

app/views/pictures/index.html.erb
<h1> listing of pujas pictures </h1>

<% @pictures.each do |picture| %>


    <p>Tile: <%= picture.title %> </p>
    <%= image_tag picture.picture_image.thumb.url %>
    <p>Description:<br> <%= picture.description.truncate_words(25) %> </p>

    <%= link_to 'Click on more details to see picture', picture_path(picture) %> <br>
     <br>
     <%= link_to 'Edit', edit_picture_path(picture) %>
     <%= link_to 'Destroy', picture_path(picture),
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

<% end %>

  <%= link_to 'New picture', new_picture_path %>

  <%= link_to 'Home', root_path %>

app/views/pictures/new.html.erb
<h1>Post a new picture here</h1>



<%= form_for :picture, url: pictures_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :picture_image %>
    <%= f.file_field :picture_image %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<h1> Picture </h1>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<p>
  <%= image_tag @picture.picture_image.url %>
</p>

<%= link_to 'Back', pictures_path %>

app/views/pujas/edit.html.erb
<h1>Edit puja here</h1>



<%= form_for :puja, url: puja_path(@puja), method: :patch do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :benefit %><br>
    <%= f.text_area :benefit %>
  </p>

  <p>
    <%= f.label :suggested_offering %><br>
    <%= f.text_field :suggested_offering %>
  </p>


  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', pujas_path %>

app/views/pujas/index.html.erb
<h1> listing of pujas available </h1>
<p> Pujas are religious ceromonies for invoking blessings
  for particular reasons. On a wordly level pujas help to provide
positive engeries to furfill our worldly wishes such as good health and being
free from life obstacles. But on the utimate level it plant the root for us to
reconize the non-duality of relative and absolute truth. </p>

<p> Your money will go directly to buying offerings and to the monks </p>
<p> Our monks typically live under 1 USD a day, and is totally reliant on kind hearted people
  like you to sponsor their livelyhood. Although we would still perform the puja even if less
then the amount is given, altough the monks would still provide their best </p>

<p> we do not get a single cent, except the fees needed for transfer </p>
<br>

<% @pujas.each do |puja| %>

    <p>Name: <%= puja.name %> </p>
    <p>Descriptions:<br> <%= puja.description.truncate_words(25) %> </p>
    <p>Benefit:<br> <%= puja.benefit.truncate_words(25) %> </p>
    <p>Suggested_offering: <%= puja.suggested_offering %> </p>
    <%= link_to 'Show', puja_path(puja) %>
    <%= link_to 'Edit', edit_puja_path(puja) %>
    <%= link_to 'Destroy', puja_path(puja),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

<% end %>

<%= link_to 'New puja', new_puja_path %>

<%= link_to 'Home', root_path %>

app/views/pujas/new.html.erb
<h1>Post a new puja here</h1>



<%= form_for :puja, url: pujas_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :benefit %><br>
    <%= f.text_area :benefit %>
  </p>

  <p>
    <%= f.label :suggested_offering %><br>
    <%= f.text_field :suggested_offering %>
  </p>


  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', pujas_path %>

app/views/pujas/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @puja.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @puja.description %>
</p>

<p>
  <strong>Benefit:</strong>
  <%= @puja.benefit %>
</p>

<p>
  <strong>Suggested_offering:</strong>
  <%= @puja.suggested_offering %>
</p>